[package]
name = "printerator"
version = "0.9.0"
edition = "2024"
license = "EUPL-1.2"
description = "simply print iterators without collecting them"

[dependencies]
parking_lot = { version = "0.12.5", default-features = false }
